/**
 * plain-english explanations shown anywhere a part needs a quick description.
 *
 * this catalog is intentionally independent from PartsLibrary so content and
 * part wiring can be integrated separately.
 */
export const PART_DESCRIPTIONS = Object.freeze({
    core: 'the required center of your ship. lose it and the ship is done.',
    hull: 'basic armor that adds health without doing anything fancy.',
    gun_basic: 'fires simple, accurate bullets at a steady pace.',
    railgun: 'charges a long beam that hits very hard in a straight line.',
    lps: 'fires a fast burst of tiny laser shots.',
    scattr: 'fires a wide cloud of pellets for close-range damage.',
    ggbm: 'launches a heavy guided missile that chases enemies.',
    rocketle: 'fires two small rockets in a quick burst.',
    minigun: 'fires faster as you hold the trigger, then overheats.',
    custom_1768676906827: 'adds a little speed and helps the ship turn.',
    custom_1767997148612: 'a long, light piece of basic armor.',
    custom_1767997495375: 'adds a little speed to your ship.',
    custom_1767998101819: 'a large block of sturdy armor.',
    custom_1767999386292: 'fires a strong, accurate laser shot.',
    custom_1767999991728: 'makes every installed laser weapon fire 5% faster.',
    custom_1768036702131: 'fires a large burst of explosive rockets.',
    custom_1768035239205: 'adds health and slowly repairs your ship.',
    custom_1768129891617: 'adds one extra rocket to every rocket burst.',
    custom_1768392079955: 'lets you dash with shift; more boosters shorten the cooldown.',
    custom_1768397007593: 'charges a long energy slash that cuts through targets.',
    custom_1768410456823: 'adds a large rechargeable shield and lets the ship face your cursor.',
    custom_1768410823264: 'adds a small rechargeable shield around this part.',
    custom_1768857172136: 'fires slow, powerful bullets from long range.',
    custom_1769204337665: 'fires three bullets in a quick burst.',
    custom_1769336961268: 'deals tiny damage but freezes enemies if you keep the beam on them.',
    custom_1769514097773: 'throws a grenade that splits into ten smaller explosions.',
    custom_1769974460678: 'launches a large pack of basic all-purpose combat drones.',
    custom_1769995907207: 'a long strip of basic armor for connecting ship sections.',
    custom_1769996177427: 'a small angled piece of basic armor.',
    custom_1769996267734: 'a long open-frame piece of basic armor.',
    drone_needle_nest: 'launches two fragile drones that fire quick, accurate bullets.',
    drone_interceptor_rack: 'launches fast drones that hunt enemy drones before other targets.',
    drone_torch_kennel: 'launches close-range laser drones with very fast attacks.',
    drone_lance_cradle: 'launches one fragile sniper drone that fires from far away.',
    drone_bombard_roost: 'launches slow rocket drones with heavy explosions.',
    drone_flak_nursery: 'launches drones that fire a wide close-range pellet fan.',
    drone_bastion_foundry: 'launches two slow, heavily armored laser drones.',
    drone_repair_choir: 'launches support drones that repair the most damaged friendly ship.',
    drone_ram_hive: 'launches fast drones that crash into enemies and explode.',
    drone_storm_lattice: 'launches five tough drones that fire two laser shots at once.',
    warp_gate: 'select with q, then right-click toward your cursor to blink a short distance.',
    mine_placer: 'fires mines that arm, wait, and explode when an enemy comes close.',
    captain_seat: 'zooms the camera out so you can see more of the room.',
    beam_sword: 'swings a short energy blade that hits hard up close.',
    shrapnel_grenade: 'throws a grenade that bursts into damaging metal fragments.',
    decoy: 'select with q, then right-click toward your cursor to drop a fake ship that distracts enemies.',
    stealth: 'select with q, then right-click to hide from enemies; firing or taking damage reveals you.',
    hack_dart: 'hits a normal enemy and makes it fight for you for a short time.',
    auto_aim: 'nudges your shots toward the enemy closest to your cursor.',
    prism: 'splits each laser shot into a weaker three-way fan.',
    emp: 'select with q, then right-click to briefly stop nearby enemies from moving or shooting.',
    fmj: 'makes bullets hit 10% harder and pass through one extra target.',
    patch_plate: 'small heavy armor with more health than a basic hull block.',
    keel_beam: 'a long reinforced hull piece for building a tough ship spine.',
    bulkhead: 'a large slab of armor that trades speed for lots of health.',
    coffin_hull: 'enormous armor with enormous weight for ships that refuse to die.',
    glasswing: 'very light armor that also helps the ship turn faster.',
    engine_brace: 'light armor that gives your engines a small speed boost.',
    salvage_magnet: 'pulls loot toward your ship from twice as far away.',
    coolant_loop: 'makes every weapon on your ship fire 8% faster.',
    gyro_ring: 'helps heavy ships turn much faster.',
    rangefinder: 'makes every moving shot travel 20% faster.',
    needler: 'fires tiny bullets extremely quickly.',
    twin_dart: 'fires two accurate bullets side by side.',
    heavy_slugger: 'fires one slow, heavy bullet that hits hard.',
    burst_cannon: 'fires five bullets in one tight burst.',
    ricochet_cannon: 'fires bullets that bounce once to another nearby enemy.',
    arc_welder: 'sprays a very short laser beam for close-range damage.',
    pulse_lance: 'fires strong, accurate laser pulses.',
    lightning_rod: 'fires a laser that jumps to two nearby enemies.',
    micro_missile_pod: 'fires three small guided missiles.',
    torpedo_tube: 'launches a slow torpedo with a huge explosion.'
});
